/**
 * @file offsets_template.h
 * @brief Template for generated offset header files
 * 
 * DO NOT EDIT MANUALLY - This is generated by UE5 Offset Dumper
 * Auto-generated offset header for reverse engineering projects
 */

#pragma once

#include <cstdint>

/**
 * @namespace Offsets
 * @brief Contains all discovered UE5 engine offsets
 */
namespace Offsets
{
    /// Global object array - contains all UObject instances
    constexpr uint64_t GObjects = 0x0;

    /// Global names pool - FName string storage
    constexpr uint64_t GNames = 0x0;

    /// World pointer - current game world instance
    constexpr uint64_t GWorld = 0x0;

    /// Engine singleton - main engine instance
    constexpr uint64_t GEngine = 0x0;
}  // namespace Offsets
