#pragma once

#define NOSTALGIA_VERSION_MAJOR 1
#define NOSTALGIA_VERSION_MINOR 8
#define NOSTALGIA_VERSION_PATCH 0
#define NOSTALGIA_VERSION_TAG "BETA"

#define NOSTALGIA_VERSION_STR "1.8.0-BETA"
#define NOSTALGIA_TITLE "Nostalgia"
#define NOSTALGIA_AUTHOR "Production Build"

#define NOSTALGIA_BUILD_DATE __DATE__
#define NOSTALGIA_BUILD_TIME __TIME__
