#include "dumper.h"
#include "memory.h"
#include "version.h"
#include <chrono>
#include <filesystem>
#include <cctype>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <map>
#include <sstream>

namespace Dumper
{
    namespace
    {
        std::string ToOffsetMacroKey(const std::string& key)
        {
            std::string out;
            out.reserve(key.size());
            for (char c : key)
            {
                if (std::isalnum(static_cast<unsigned char>(c)))
                    out += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
                else
                    out += '_';
            }
            return out;
        }

        void AppendJsonEscaped(std::ostringstream& o, const std::string& s)
        {
            for (unsigned char c : s)
            {
                switch (c)
                {
                    case '\\':
                        o << "\\\\";
                        break;
                    case '"':
                        o << "\\\"";
                        break;
                    case '\n':
                    case '\r':
                    case '\t':
                        o << ' ';
                        break;
                    default:
                        o << static_cast<char>(c);
                        break;
                }
            }
        }

        void JsonQuoted(std::ostringstream& o, const std::string& s)
        {
            o << '"';
            AppendJsonEscaped(o, s);
            o << '"';
        }

        std::string SanitizeHeaderComment(std::string s)
        {
            for (char& c : s)
            {
                if (c == '\n' || c == '\r' || c == '*')
                    c = ' ';
            }
            if (s.size() > 220)
                s.resize(220);
            return s;
        }

        void EmitOffsetGlobal(std::ostringstream& header, const char* cppName, const OffsetInfo& info)
        {
            if (!info.address)
            {
                header << "    // " << cppName << " (not found)\n";
                return;
            }
            header << "    // " << cppName << " | module: " << SanitizeHeaderComment(info.moduleName) << " | sig: "
                   << SanitizeHeaderComment(info.signature) << "\n";
            header << "    constexpr std::uintptr_t " << cppName << " = 0x" << std::hex << std::uppercase << info.address
                   << ";\n";
        }
    }

    std::string GenerateHeaderContent(const DiscoveredOffsets& offsets, const std::string& gameName,
        const std::map<std::string, u64>* extraSymbols)
    {
        std::ostringstream header;

        auto now = std::chrono::system_clock::now();
        auto time_t_now = std::chrono::system_clock::to_time_t(now);

        char timeBuf[64] = {};
        if (ctime_s(timeBuf, sizeof(timeBuf), &time_t_now) != 0)
            timeBuf[0] = '\0';

        header << "#pragma once\n";
        header << "\n";
        header << "/**\n";
        header << " * @file offsets.h\n";
        header << " * @brief Unreal Engine offsets for " << gameName << "\n";
        header << " * @note Auto-generated by " << NOSTALGIA_TITLE << " v" << NOSTALGIA_VERSION_STR << "\n";
        header << " * @date " << timeBuf;
        header << " */\n";
        header << "\n";
        header << "#include <cstdint>\n";
        header << "#include <type_traits>\n";
        header << "\n";

        header << "namespace Offsets\n";
        header << "{\n";
        header << "    // Core globals (see companion *_dump.json for full sigs / class hints)\n";
        EmitOffsetGlobal(header, "GObjects", offsets.GObjects);
        EmitOffsetGlobal(header, "GNames", offsets.GNames);
        EmitOffsetGlobal(header, "GWorld", offsets.GWorld);
        EmitOffsetGlobal(header, "GEngine", offsets.GEngine);
        header << "\n";

        if (!offsets.customOffsets.empty())
        {
            header << "    // Additional globals (pattern- or heuristic-derived)\n";
            for (const auto& kv : offsets.customOffsets)
            {
                if (!kv.second.address)
                    continue;
                header << "    // " << SanitizeHeaderComment(kv.first) << " | module: "
                       << SanitizeHeaderComment(kv.second.moduleName) << " | sig: "
                       << SanitizeHeaderComment(kv.second.signature) << "\n";
                header << "    constexpr std::uintptr_t " << ToOffsetMacroKey(kv.first) << " = 0x" << std::hex
                       << std::uppercase << kv.second.address << ";\n";
            }
            header << "\n";
        }

        if (extraSymbols && !extraSymbols->empty())
        {
            header << "    // Engine symbols (export / harvest)\n";
            for (const auto& kv : *extraSymbols)
            {
                header << "    constexpr std::uintptr_t " << ToOffsetMacroKey(kv.first) << " = 0x" << std::hex
                       << std::uppercase << kv.second << ";\n";
            }
            header << "\n";
        }

        header << "    // Member layout offsets\n";
        for (const auto& kv : offsets.layoutMemberOffsets)
        {
            header << "    constexpr std::uint32_t " << ToOffsetMacroKey(kv.first) << " = 0x" << std::hex << std::uppercase
                   << kv.second << ";\n";
        }

        header << "} // namespace Offsets\n";
        return header.str();
    }

    std::string GenerateFullDumpJson(const DiscoveredOffsets& offsets, const std::string& gameName,
        const std::map<std::string, u64>* extraSymbols)
    {
        std::ostringstream j;
        j << "{\n";
        j << "  \"tool\": \"";
        AppendJsonEscaped(j, NOSTALGIA_TITLE);
        j << "\",\n";
        j << "  \"version\": \"" << NOSTALGIA_VERSION_STR << "\",\n  \"game\": ";
        JsonQuoted(j, gameName);
        j << ",\n";

        auto emitOffsetBlock = [&](const char* key, const OffsetInfo& o) {
            j << "    \"" << key << "\": ";
            if (!o.address)
            {
                j << "null";
                return;
            }
            j << "{ \"address\": \"0x" << std::hex << std::uppercase << o.address << std::dec << "\", \"module\": ";
            JsonQuoted(j, o.moduleName);
            j << ", \"signature\": ";
            JsonQuoted(j, o.signature);
            j << " }";
        };

        j << "  \"globals\": {\n";
        emitOffsetBlock("GObjects", offsets.GObjects);
        j << ",\n";
        emitOffsetBlock("GNames", offsets.GNames);
        j << ",\n";
        emitOffsetBlock("GWorld", offsets.GWorld);
        j << ",\n";
        emitOffsetBlock("GEngine", offsets.GEngine);
        j << "\n  },\n";

        j << "  \"custom_offsets\": {\n";
        {
            size_t i = 0;
            for (const auto& kv : offsets.customOffsets)
            {
                if (i++)
                    j << ",\n";
                j << "    \"";
                AppendJsonEscaped(j, kv.first);
                j << "\": ";
                if (!kv.second.address)
                    j << "null";
                else
                {
                    j << "{ \"address\": \"0x" << std::hex << std::uppercase << kv.second.address << std::dec
                      << "\", \"module\": ";
                    JsonQuoted(j, kv.second.moduleName);
                    j << ", \"signature\": ";
                    JsonQuoted(j, kv.second.signature);
                    j << " }";
                }
            }
        }
        j << "\n  },\n";

        j << "  \"engine_symbols\": ";
        if (!extraSymbols || extraSymbols->empty())
            j << "{}";
        else
        {
            j << "{\n";
            size_t i = 0;
            for (const auto& kv : *extraSymbols)
            {
                if (i++)
                    j << ",\n";
                j << "    \"";
                AppendJsonEscaped(j, kv.first);
                j << "\": \"0x" << std::hex << std::uppercase << kv.second << std::dec << "\"";
            }
            j << "\n  }";
        }
        j << ",\n";

        j << "  \"layout_member_offsets\": {\n";
        {
            size_t i = 0;
            for (const auto& kv : offsets.layoutMemberOffsets)
            {
                if (i++)
                    j << ",\n";
                j << "    \"";
                AppendJsonEscaped(j, kv.first);
                j << "\": \"0x" << std::hex << std::uppercase << kv.second << std::dec << "\"";
            }
        }
        j << "\n  },\n";

        j << "  \"script_path_hints\": [\n";
        for (size_t i = 0; i < offsets.scriptPathHints.size(); ++i)
        {
            if (i)
                j << ",\n";
            j << "    ";
            JsonQuoted(j, offsets.scriptPathHints[i]);
        }
        j << "\n  ],\n";

        j << "  \"uobject_samples\": [\n";
        for (size_t i = 0; i < offsets.uobjectSamples.size(); ++i)
        {
            if (i)
                j << ",\n";
            j << "    ";
            JsonQuoted(j, offsets.uobjectSamples[i]);
        }
        j << "\n  ]\n}\n";
        return j.str();
    }

    std::string GenerateJsonContent(const DiscoveredOffsets& offsets, const std::string& gameName,
        const std::map<std::string, u64>* extraSymbols)
    {
        std::ostringstream json;
        json << "{\n";
        json << "  \"tool\": \"" << NOSTALGIA_TITLE << "\",\n";
        json << "  \"version\": \"" << NOSTALGIA_VERSION_STR << "\",\n";
        json << "  \"game\": \"" << gameName << "\",\n";
        json << "  \"offsets\": {\n";

        auto addOffset = [&](const char* key, u64 addr, bool last = false) {
            json << "    \"" << key << "\": \"0x" << std::hex << std::uppercase << addr << "\"" << (last ? "" : ",")
                 << "\n";
        };

        addOffset("GObjects", offsets.GObjects.address);
        addOffset("GNames", offsets.GNames.address);
        addOffset("GWorld", offsets.GWorld.address);
        addOffset("GEngine", offsets.GEngine.address,
            (offsets.customOffsets.empty() && (!extraSymbols || extraSymbols->empty()) && offsets.layoutMemberOffsets.empty()));

        json << "  }\n";
        json << "}\n";
        return json.str();
    }

    std::string GenerateSymbolPackHeader(const std::map<std::string, u64>& symbols, const std::string& gameName,
        const std::string& engineTag)
    {
        std::ostringstream h;
        h << "#pragma once\n";
        h << "/** " << NOSTALGIA_TITLE << " v" << NOSTALGIA_VERSION_STR << " | " << engineTag << " | " << gameName << " */\n";
        h << "#include <cstdint>\n\nnamespace EngineSymbols {\n";
        for (const auto& kv : symbols)
            h << "    constexpr std::uintptr_t " << ToOffsetMacroKey(kv.first) << " = 0x" << std::hex << std::uppercase
              << kv.second << ";\n";
        h << "} // namespace EngineSymbols\n";
        return h.str();
    }

    std::string GenerateSymbolPackJson(const std::map<std::string, u64>& symbols, const std::string& engineTag,
        const std::string& gameName)
    {
        std::ostringstream j;
        j << "{\n  \"tool\": \"";
        AppendJsonEscaped(j, NOSTALGIA_TITLE);
        j << "\",\n  \"version\": \"" << NOSTALGIA_VERSION_STR << "\",\n  \"engine\": ";
        JsonQuoted(j, engineTag);
        j << ",\n  \"game\": ";
        JsonQuoted(j, gameName);
        j << ",\n  \"symbol_count\": " << std::dec << symbols.size() << ",\n  \"symbols\": {\n";
        size_t i = 0;
        for (const auto& kv : symbols)
        {
            if (i++)
                j << ",\n";
            j << "    \"";
            AppendJsonEscaped(j, kv.first);
            j << "\": \"0x" << std::hex << std::uppercase << kv.second << std::dec << "\"";
        }
        j << "\n  }\n}\n";
        return j.str();
    }

    Result WriteHeaderFile(const DiscoveredOffsets& offsets, const std::string& outputPath, const std::string& gameName,
        const std::map<std::string, u64>* extraSymbols)
    {
        std::ofstream f(outputPath, std::ios::binary);
        if (!f)
            return { ScanResult::FileWriteFailed, "Cannot open path" };
        f << GenerateHeaderContent(offsets, gameName, extraSymbols);
        return { ScanResult::Success, "OK" };
    }

    Result WriteSymbolPack(const std::map<std::string, u64>& symbols, const std::string& outputDirectory,
        const std::string& fileStem, const std::string& gameName, const std::string& engineTag)
    {
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::create_directories(outputDirectory, ec);
        const fs::path dir(outputDirectory);
        const fs::path hPath = dir / (fileStem + ".h");
        const fs::path jPath = dir / (fileStem + ".json");
        std::ofstream hf(hPath.string(), std::ios::binary);
        std::ofstream jf(jPath.string(), std::ios::binary);
        if (!hf || !jf)
            return { ScanResult::FileWriteFailed, "Cannot write symbol pack" };
        hf << GenerateSymbolPackHeader(symbols, gameName, engineTag);
        jf << GenerateSymbolPackJson(symbols, engineTag, gameName);
        return { ScanResult::Success, "OK" };
    }

    bool ValidateOffsets(const DiscoveredOffsets& offsets)
    {
        auto ok = [](u64 a) { return a == 0 || Memory::IsValidAddress(a); };
        return ok(offsets.GObjects.address) && ok(offsets.GNames.address) && ok(offsets.GWorld.address)
            && ok(offsets.GEngine.address);
    }

    bool VerifyUnrealGlobals(HANDLE /*handle*/, const DiscoveredOffsets& /*offsets*/, std::string& outDetails)
    {
        outDetails = "Not implemented in this build.\n";
        return false;
    }
}
